# Generated by Django 3.0.7 on 2020-06-10 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolshed_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='thumbs_count',
        ),
    ]
